site_name: Meal of Record
theme: material

nav:
  - Home: index.md
  - Concepts: concepts.md
  - Search & Logging: search_logging.md
  - Recipes: recipes.md
  - Goals: goals.md
  - Data & Storage: data_management.md
  - About: about.md
  
